"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy
import surface; this module's content relocated to
`cjm_transcription_adapter_interface` at execution stage 2 (pass-2 Thread 3
interface-library dissolution).

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = ['TranscriptionResult']

# %% ../nbs/core.ipynb #90ce73a0
# REMOVE-AFTER-OVERHAUL(option-c-cascade): re-export shim; the classes
# live in cjm_transcription_adapter_interface.core (born-final home).
from cjm_transcription_adapter_interface.core import TranscriptionResult

# %% ../nbs/core.ipynb #0894ff18
_all_ = ['TranscriptionResult']
