"""Standardized SQLite storage for forced alignment results with content hashing

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemforced_alignment_storage.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/forced_alignment_storage.ipynb.

# %% auto #0
__all__ = ['ForcedAlignmentRow', 'ForcedAlignmentStorage']

# %% ../nbs/forced_alignment_storage.ipynb #cell-imports
import json
import logging
import sqlite3
import time
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from cjm_plugin_system.utils.hashing import hash_bytes, hash_file

# %% ../nbs/forced_alignment_storage.ipynb #cell-row
@dataclass
class ForcedAlignmentRow:
    """A single row from the forced_alignments table."""
    job_id: str          # Unique job identifier
    audio_path: str      # Path to the source audio file
    audio_hash: str      # Hash of source audio in "algo:hexdigest" format
    text: str            # Input transcript text that was aligned
    text_hash: str       # Hash of input text in "algo:hexdigest" format
    config_hash: str     # Hash of the effective alignment config used
    items: Optional[List[Dict[str, Any]]] = None  # Serialized ForcedAlignItems
    metadata: Optional[Dict[str, Any]] = None      # Plugin metadata
    created_at: Optional[float] = None             # Unix timestamp

# %% ../nbs/forced_alignment_storage.ipynb #cell-storage
class ForcedAlignmentStorage:
    """Standardized SQLite storage for forced alignment results."""

    SCHEMA = """
        CREATE TABLE IF NOT EXISTS forced_alignments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            job_id TEXT UNIQUE NOT NULL,
            audio_path TEXT NOT NULL,
            audio_hash TEXT NOT NULL,
            text TEXT NOT NULL,
            text_hash TEXT NOT NULL,
            config_hash TEXT NOT NULL DEFAULT '',
            items JSON,
            metadata JSON,
            created_at REAL NOT NULL
        )
    """

    INDEX = "CREATE INDEX IF NOT EXISTS idx_forced_alignments_job_id ON forced_alignments(job_id);"

    # Cache/upsert key: one row per (audio_path, text_hash, config_hash). The input
    # is the (audio, transcript) pair — text_hash is in the key (different transcript
    # = distinct result). INSERT OR REPLACE overwrites on re-run; get_cached
    # additionally filters on audio_hash for content-correctness.
    CACHE_INDEX = (
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_forced_alignments_cache "
        "ON forced_alignments(audio_path, text_hash, config_hash);"
    )

    def __init__(
        self,
        db_path: str  # Absolute path to the SQLite database file
    ):
        """Initialize storage, create table, run migrations, and build indexes."""
        self.db_path = db_path
        with sqlite3.connect(self.db_path) as con:
            con.execute(self.SCHEMA)
            self._migrate(con)
            con.execute(self.INDEX)
            con.execute(self.CACHE_INDEX)

    def _migrate(
        self,
        con: sqlite3.Connection  # Open connection (within the __init__ transaction)
    ) -> None:
        """Add columns introduced after the original schema (idempotent).

        Pre-cache tables lack `config_hash`; add it with an empty-string default.
        Existing rows become unreachable via get_cached (config_hash='' won't match
        a real config hash) — intentional, alignments are regenerable."""
        cols = {r[1] for r in con.execute("PRAGMA table_info(forced_alignments)").fetchall()}
        if "config_hash" not in cols:
            con.execute("ALTER TABLE forced_alignments ADD COLUMN config_hash TEXT NOT NULL DEFAULT ''")

    def save(
        self,
        job_id: str,        # Unique job identifier
        audio_path: str,    # Path to the source audio file
        audio_hash: str,    # Hash of source audio in "algo:hexdigest" format
        text: str,          # Input transcript text
        text_hash: str,     # Hash of input text in "algo:hexdigest" format
        config_hash: str,   # Hash of the effective alignment config
        items: Optional[List[Dict[str, Any]]] = None,  # Serialized ForcedAlignItems
        metadata: Optional[Dict[str, Any]] = None       # Plugin metadata
    ) -> None:
        """Save or replace a forced alignment result (upsert by audio_path + text_hash + config_hash)."""
        with sqlite3.connect(self.db_path) as con:
            con.execute(
                """INSERT OR REPLACE INTO forced_alignments
                   (job_id, audio_path, audio_hash, text, text_hash, config_hash,
                    items, metadata, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    job_id,
                    audio_path,
                    audio_hash,
                    text,
                    text_hash,
                    config_hash,
                    json.dumps(items) if items else None,
                    json.dumps(metadata) if metadata else None,
                    time.time()
                )
            )

    def save_with_logging(
        self,
        *,
        job_id: str,        # Unique job identifier
        audio_path: str,    # Path to the source audio file
        audio_hash: str,    # Hash of source audio in "algo:hexdigest" format
        text: str,          # Input transcript text
        text_hash: str,     # Hash of input text in "algo:hexdigest" format
        config_hash: str,   # Hash of the effective alignment config
        items: Optional[List[Dict[str, Any]]] = None,  # Serialized ForcedAlignItems
        metadata: Optional[Dict[str, Any]] = None,      # Plugin metadata
        logger: Optional[logging.Logger] = None         # Optional logger for success/failure messages
    ) -> bool:  # True if saved; False if the save failed (error logged, not raised)
        """Save a result, logging success/failure. Failures are logged and swallowed (returns False).

        Centralizes the try/save/log/except block every forced-alignment plugin reimplements.
        Returns True on success so callers can gate post-save side effects on the result."""
        try:
            self.save(
                job_id=job_id,
                audio_path=audio_path,
                audio_hash=audio_hash,
                text=text,
                text_hash=text_hash,
                config_hash=config_hash,
                items=items,
                metadata=metadata,
            )
            if logger:
                logger.info(f"Saved result to DB (Job: {job_id})")
            return True
        except Exception as e:
            if logger:
                logger.error(f"Failed to save to DB: {e}")
            return False

    def get_cached(
        self,
        audio_path: str,   # Path to the source audio file
        audio_hash: str,   # Content hash of the audio (cache miss if the file changed)
        text_hash: str,    # Hash of the input transcript text (part of the cache key)
        config_hash: str   # Hash of the effective alignment config
    ) -> Optional[ForcedAlignmentRow]:  # Cached row or None
        """Retrieve a content-correct cached alignment for an (audio, transcript) pair.

        Matches on audio_path + audio_hash + text_hash + config_hash. A changed audio
        file (new audio_hash) misses even if a stale row exists at the same
        (audio_path, text_hash, config_hash) — the next save() replaces it."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, text, text_hash, config_hash,
                          items, metadata, created_at
                   FROM forced_alignments
                   WHERE audio_path = ? AND audio_hash = ? AND text_hash = ? AND config_hash = ?""",
                (audio_path, audio_hash, text_hash, config_hash)
            )
            row = cur.fetchone()
            return self._row(row) if row else None

    def get_by_job_id(
        self,
        job_id: str  # Job identifier to look up
    ) -> Optional[ForcedAlignmentRow]:  # Row or None if not found
        """Retrieve a forced alignment result by job ID."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, text, text_hash, config_hash,
                          items, metadata, created_at
                   FROM forced_alignments WHERE job_id = ?""",
                (job_id,)
            )
            row = cur.fetchone()
            return self._row(row) if row else None

    def list_jobs(
        self,
        limit: int = 100  # Maximum number of rows to return
    ) -> List[ForcedAlignmentRow]:  # List of forced alignment rows
        """List forced alignment jobs ordered by creation time (newest first)."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, text, text_hash, config_hash,
                          items, metadata, created_at
                   FROM forced_alignments ORDER BY created_at DESC LIMIT ?""",
                (limit,)
            )
            return [self._row(row) for row in cur]

    @staticmethod
    def _row(
        row: tuple  # Raw SQLite row tuple in canonical column order
    ) -> ForcedAlignmentRow:  # Parsed row dataclass
        """Build a ForcedAlignmentRow from a raw column tuple."""
        return ForcedAlignmentRow(
            job_id=row[0],
            audio_path=row[1],
            audio_hash=row[2],
            text=row[3],
            text_hash=row[4],
            config_hash=row[5],
            items=json.loads(row[6]) if row[6] else None,
            metadata=json.loads(row[7]) if row[7] else None,
            created_at=row[8]
        )

    def verify_audio(
        self,
        job_id: str  # Job identifier to verify
    ) -> Optional[bool]:  # True if audio matches, False if tampered, None if job not found
        """Verify the source audio file still matches its stored hash."""
        row = self.get_by_job_id(job_id)
        if not row:
            return None
        current_hash = hash_file(row.audio_path)
        return current_hash == row.audio_hash

    def verify_text(
        self,
        job_id: str  # Job identifier to verify
    ) -> Optional[bool]:  # True if text matches, False if tampered, None if job not found
        """Verify the input text still matches its stored hash."""
        row = self.get_by_job_id(job_id)
        if not row:
            return None
        current_hash = hash_bytes(row.text.encode())
        return current_hash == row.text_hash
