"""Domain-specific plugin interface for word-level audio-text alignment

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemforced_alignment_interface.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/forced_alignment_interface.ipynb.

# %% auto #0
__all__ = ['ForcedAlignmentPlugin']

# %% ../nbs/forced_alignment_interface.ipynb #cell-imports
from abc import abstractmethod
from pathlib import Path
from typing import List, Union

from cjm_plugin_system.core.interface import PluginInterface

from .forced_alignment_core import ForcedAlignResult

# %% ../nbs/forced_alignment_interface.ipynb #cell-interface
class ForcedAlignmentPlugin(PluginInterface):
    """
    Abstract base class for all forced alignment plugins.

    Extends PluginInterface with forced-alignment-specific requirements:
    - `supported_formats`: List of audio file extensions this plugin can handle
    - `execute`: Accepts an audio file path and transcript text, returns ForcedAlignResult

    Input contract: plugins receive a path to a decodable audio file. Producing a
    model-ready file (format / sample-rate / channel normalization) is the caller's
    responsibility — e.g. an upstream ffmpeg step in the orchestration pipeline —
    not the plugin's. This keeps the interface library dependency-light.
    """

    entry_point_group = "transcription.forced_alignment_plugins"

    @property
    @abstractmethod
    def supported_formats(self) -> List[str]:  # e.g., ['wav', 'mp3', 'flac']
        """List of supported audio file extensions (without the dot)."""
        ...

    @abstractmethod
    def execute(
        self,
        audio: Union[str, Path],  # Path to a decodable audio file
        text: str,                # Transcript text to align against
        **kwargs
    ) -> ForcedAlignResult:  # Word-level alignment result
        """
        Perform forced alignment of text against audio.

        `audio` is a path to a decodable audio file; the caller guarantees it is in
        a form the plugin/model can consume.
        """
        ...
