"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy
import surface; this module's content relocated to
`cjm_forced_alignment_adapter_interface` at execution stage 2 (pass-2 Thread 3
interface-library dissolution).

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemforced_alignment_storage.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/forced_alignment_storage.ipynb.

# %% auto #0
__all__ = ['ForcedAlignmentRow', 'ForcedAlignmentStorage']

# %% ../nbs/forced_alignment_storage.ipynb #2a6cbc64
# REMOVE-AFTER-OVERHAUL(option-c-cascade): re-export shim; the classes
# live in cjm_forced_alignment_adapter_interface.storage (born-final home).
from cjm_forced_alignment_adapter_interface.storage import ForcedAlignmentRow, ForcedAlignmentStorage

# %% ../nbs/forced_alignment_storage.ipynb #01cc909e
_all_ = ['ForcedAlignmentRow', 'ForcedAlignmentStorage']
