"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy
import surface; this module's content relocated to
`cjm_forced_alignment_adapter_interface` at execution stage 2 (pass-2 Thread 3
interface-library dissolution).

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemforced_alignment_core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/forced_alignment_core.ipynb.

# %% auto #0
__all__ = ['ForcedAlignItem', 'ForcedAlignResult']

# %% ../nbs/forced_alignment_core.ipynb #979e19cc
# REMOVE-AFTER-OVERHAUL(option-c-cascade): re-export shim; the classes
# live in cjm_forced_alignment_adapter_interface.core (born-final home).
from cjm_forced_alignment_adapter_interface.core import ForcedAlignItem, ForcedAlignResult

# %% ../nbs/forced_alignment_core.ipynb #2d8fe6b5
_all_ = ['ForcedAlignItem', 'ForcedAlignResult']
