"""Domain-specific plugin interface for audio transcription

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemplugin_interface.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin_interface.ipynb.

# %% auto #0
__all__ = ['TranscriptionPlugin']

# %% ../nbs/plugin_interface.ipynb #9be27cb8
from abc import abstractmethod
from pathlib import Path
from typing import List, Union

from cjm_plugin_system.core.interface import PluginInterface

from .core import TranscriptionResult

# %% ../nbs/plugin_interface.ipynb #26808a7c
class TranscriptionPlugin(PluginInterface):
    """
    Abstract base class for all transcription plugins.

    Extends PluginInterface with transcription-specific requirements:
    - `supported_formats`: List of audio file extensions this plugin can handle
    - `execute`: Accepts an audio file path (str or Path), returns TranscriptionResult

    Input contract: plugins receive a path to a decodable audio file. Producing a
    model-ready file (format / sample-rate / channel normalization) is the caller's
    responsibility — e.g. an upstream ffmpeg step in the orchestration pipeline —
    not the plugin's. This keeps the interface library dependency-light (no audio
    I/O deps such as numpy/soundfile in the shared consumer environment).
    """

    # Entry point group for discovery (legacy, kept for metadata)
    entry_point_group = "transcription.plugins"

    @property
    @abstractmethod
    def supported_formats(self) -> List[str]: # e.g., ['wav', 'mp3', 'flac']
        """List of supported audio file extensions (without the dot)."""
        ...

    @abstractmethod
    def execute(
        self,
        audio: Union[str, Path], # Path to a decodable audio file
        **kwargs
    ) -> TranscriptionResult: # Transcription result with text, confidence, segments
        """
        Transcribe audio to text.

        `audio` is a path to a decodable audio file; the caller guarantees it is in
        a form the plugin/model can consume.
        """
        ...
