"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy
import surface; this module's content relocated to
`cjm_transcription_adapter_interface` at execution stage 2 (pass-2 Thread 3
interface-library dissolution).

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemstorage.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/storage.ipynb.

# %% auto #0
__all__ = ['TranscriptionRow', 'TranscriptionStorage']

# %% ../nbs/storage.ipynb #934b521d
# REMOVE-AFTER-OVERHAUL(option-c-cascade): re-export shim; the classes
# live in cjm_transcription_adapter_interface.storage (born-final home).
from cjm_transcription_adapter_interface.storage import TranscriptionRow, TranscriptionStorage

# %% ../nbs/storage.ipynb #e55bfee1
_all_ = ['TranscriptionRow', 'TranscriptionStorage']
