"""Standardized SQLite storage for transcription results with content hashing

Docs: https://cj-mills.github.io/cjm-transcription-plugin-systemstorage.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/storage.ipynb.

# %% auto #0
__all__ = ['TranscriptionRow', 'TranscriptionStorage']

# %% ../nbs/storage.ipynb #cell-imports
import json
import logging
import sqlite3
import time
from dataclasses import dataclass, asdict
from typing import Any, Dict, List, Optional

from cjm_plugin_system.utils.hashing import hash_bytes, hash_file

# %% ../nbs/storage.ipynb #cell-row-dataclass
@dataclass
class TranscriptionRow:
    """A single row from the transcriptions table."""
    job_id: str          # Unique job identifier
    audio_path: str      # Path to the source audio file
    audio_hash: str      # Hash of source audio in "algo:hexdigest" format
    config_hash: str     # Hash of the effective transcription config used
    text: str            # Transcribed text output
    text_hash: str       # Hash of transcribed text in "algo:hexdigest" format
    segments: Optional[List[Dict[str, Any]]] = None  # Timestamped segments
    metadata: Optional[Dict[str, Any]] = None        # Plugin metadata
    created_at: Optional[float] = None               # Unix timestamp

# %% ../nbs/storage.ipynb #cell-storage-class
class TranscriptionStorage:
    """Standardized SQLite storage for transcription results."""

    SCHEMA = """
        CREATE TABLE IF NOT EXISTS transcriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            job_id TEXT UNIQUE NOT NULL,
            audio_path TEXT NOT NULL,
            audio_hash TEXT NOT NULL,
            config_hash TEXT NOT NULL DEFAULT '',
            text TEXT NOT NULL,
            text_hash TEXT NOT NULL,
            segments JSON,
            metadata JSON,
            created_at REAL NOT NULL
        )
    """

    INDEX = "CREATE INDEX IF NOT EXISTS idx_transcriptions_job_id ON transcriptions(job_id);"

    # Cache/upsert key: one row per (audio_path, config_hash). INSERT OR REPLACE
    # overwrites on re-run; get_cached additionally filters on audio_hash for
    # content-correctness (a changed audio file misses, the next save replaces).
    CACHE_INDEX = (
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_transcriptions_cache "
        "ON transcriptions(audio_path, config_hash);"
    )

    def __init__(
        self,
        db_path: str  # Absolute path to the SQLite database file
    ):
        """Initialize storage, create table, run migrations, and build indexes."""
        self.db_path = db_path
        with sqlite3.connect(self.db_path) as con:
            con.execute(self.SCHEMA)
            self._migrate(con)
            con.execute(self.INDEX)
            con.execute(self.CACHE_INDEX)

    def _migrate(
        self,
        con: sqlite3.Connection  # Open connection (within the __init__ transaction)
    ) -> None:
        """Add columns introduced after the original schema (idempotent).

        Pre-cache tables lack `config_hash`; add it with an empty-string default.
        Existing rows become unreachable via get_cached (config_hash='' won't match
        a real config hash) — intentional, transcriptions are regenerable."""
        cols = {r[1] for r in con.execute("PRAGMA table_info(transcriptions)").fetchall()}
        if "config_hash" not in cols:
            con.execute("ALTER TABLE transcriptions ADD COLUMN config_hash TEXT NOT NULL DEFAULT ''")

    def save(
        self,
        job_id: str,        # Unique job identifier
        audio_path: str,    # Path to the source audio file
        audio_hash: str,    # Hash of source audio in "algo:hexdigest" format
        config_hash: str,   # Hash of the effective transcription config
        text: str,          # Transcribed text output
        text_hash: str,     # Hash of transcribed text in "algo:hexdigest" format
        segments: Optional[List[Dict[str, Any]]] = None,  # Timestamped segments
        metadata: Optional[Dict[str, Any]] = None         # Plugin metadata
    ) -> None:
        """Save or replace a transcription result (upsert by audio_path + config_hash)."""
        with sqlite3.connect(self.db_path) as con:
            con.execute(
                """INSERT OR REPLACE INTO transcriptions
                   (job_id, audio_path, audio_hash, config_hash, text, text_hash,
                    segments, metadata, created_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    job_id,
                    audio_path,
                    audio_hash,
                    config_hash,
                    text,
                    text_hash,
                    json.dumps(segments) if segments else None,
                    json.dumps(metadata) if metadata else None,
                    time.time()
                )
            )

    def save_with_logging(
        self,
        *,
        job_id: str,        # Unique job identifier
        audio_path: str,    # Path to the source audio file
        audio_hash: str,    # Hash of source audio in "algo:hexdigest" format
        config_hash: str,   # Hash of the effective transcription config
        text: str,          # Transcribed text output
        text_hash: str,     # Hash of transcribed text in "algo:hexdigest" format
        segments: Optional[List[Dict[str, Any]]] = None,  # Timestamped segments
        metadata: Optional[Dict[str, Any]] = None,        # Plugin metadata
        logger: Optional[logging.Logger] = None           # Optional logger for success/failure messages
    ) -> bool:  # True if saved; False if the save failed (error logged, not raised)
        """Save a result, logging success/failure. Failures are logged and swallowed (returns False).

        Centralizes the try/save/log/except block every transcription plugin reimplements.
        Returns True on success so callers can gate post-save side effects on the result."""
        try:
            self.save(
                job_id=job_id,
                audio_path=audio_path,
                audio_hash=audio_hash,
                config_hash=config_hash,
                text=text,
                text_hash=text_hash,
                segments=segments,
                metadata=metadata,
            )
            if logger:
                logger.info(f"Saved result to DB (Job: {job_id})")
            return True
        except Exception as e:
            if logger:
                logger.error(f"Failed to save to DB: {e}")
            return False

    def get_cached(
        self,
        audio_path: str,   # Path to the source audio file
        audio_hash: str,   # Content hash of the audio (cache miss if the file changed)
        config_hash: str   # Hash of the effective transcription config
    ) -> Optional[TranscriptionRow]:  # Cached row or None
        """Retrieve a content-correct cached transcription result.

        Matches on audio_path + audio_hash + config_hash. A changed audio file
        (new audio_hash) misses even if a stale row exists at the same
        (audio_path, config_hash) — the next save() replaces it."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, config_hash, text, text_hash,
                          segments, metadata, created_at
                   FROM transcriptions
                   WHERE audio_path = ? AND audio_hash = ? AND config_hash = ?""",
                (audio_path, audio_hash, config_hash)
            )
            row = cur.fetchone()
            return self._row(row) if row else None

    def get_by_job_id(
        self,
        job_id: str  # Job identifier to look up
    ) -> Optional[TranscriptionRow]:  # Row or None if not found
        """Retrieve a transcription result by job ID."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, config_hash, text, text_hash,
                          segments, metadata, created_at
                   FROM transcriptions WHERE job_id = ?""",
                (job_id,)
            )
            row = cur.fetchone()
            return self._row(row) if row else None

    def list_jobs(
        self,
        limit: int = 100  # Maximum number of rows to return
    ) -> List[TranscriptionRow]:  # List of transcription rows
        """List transcription jobs ordered by creation time (newest first)."""
        with sqlite3.connect(self.db_path) as con:
            cur = con.execute(
                """SELECT job_id, audio_path, audio_hash, config_hash, text, text_hash,
                          segments, metadata, created_at
                   FROM transcriptions ORDER BY created_at DESC LIMIT ?""",
                (limit,)
            )
            return [self._row(row) for row in cur]

    @staticmethod
    def _row(
        row: tuple  # Raw SQLite row tuple in canonical column order
    ) -> TranscriptionRow:  # Parsed row dataclass
        """Build a TranscriptionRow from a raw column tuple."""
        return TranscriptionRow(
            job_id=row[0],
            audio_path=row[1],
            audio_hash=row[2],
            config_hash=row[3],
            text=row[4],
            text_hash=row[5],
            segments=json.loads(row[6]) if row[6] else None,
            metadata=json.loads(row[7]) if row[7] else None,
            created_at=row[8]
        )

    def verify_audio(
        self,
        job_id: str  # Job identifier to verify
    ) -> Optional[bool]:  # True if audio matches, False if tampered, None if job not found
        """Verify the source audio file still matches its stored hash."""
        row = self.get_by_job_id(job_id)
        if not row:
            return None
        current_hash = hash_file(row.audio_path)
        return current_hash == row.audio_hash

    def verify_text(
        self,
        job_id: str  # Job identifier to verify
    ) -> Optional[bool]:  # True if text matches, False if tampered, None if job not found
        """Verify the transcription text still matches its stored hash."""
        row = self.get_by_job_id(job_id)
        if not row:
            return None
        current_hash = hash_bytes(row.text.encode())
        return current_hash == row.text_hash
